{
    "name": "PlasticOS CRM Sync",
    "version": "19.0.1.6.2",
    "summary": "API-first CRM sync (VanillaSoft live; other providers stubbed)",
    "author": "Igor Beylin",
    "license": "LGPL-3",
    "category": "PlasticOS",
    "depends": [
        "base",
        "base_setup",
        "crm",
        "mail",
        "utm",
        "plasticos_base",
        "plasticos_security_base",
        "plasticos_crm_bridge",
        "plasticos_facility_profile",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/crm_connection_views.xml",
        "views/crm_sync_run_views.xml",
        "views/crm_call_event_views.xml",
        "views/crm_lead_sync_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
