{
    "name": "PlasticOS Automation Layer",
    "version": "19.0.2.1.0",
    "summary": "Deterministic workflow automation: approvals, reminders, logistics follow-ups, SLA monitoring",
    "author": "PlasticOS",
    "license": "LGPL-3",
    "depends": [
        "plasticos_base",
        "base",
        "base_automation",
        "mail",
        "product",
        "sale_management",
        "account",
        "stock",
        "purchase",
        "plasticos_logistics",
        "plasticos_transaction",
        "plasticos_claims",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/automation_config_data.xml",
        "data/config_parameters.xml",
        "data/sale_approval_cron.xml",
        "data/invoice_reminder_cron.xml",
        "data/contract_renewal_cron.xml",
        "data/stock_alert_cron.xml",
        "data/email_templates.xml",
        "data/cron_supplier_followup.xml",
        "data/cron_trucker_followup.xml",
        "data/cron_load_sla.xml",
        "data/workflow_automations.xml",
        "views/automation_config_views.xml",
        "views/automation_log_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
