{
    "name": "PlasticOS Intake",
    "version": "19.0.5.1.0",
    "summary": "Transactional Material Intake — contact intelligence, smart memory, UX normalization",
    "author": "Igor Beylin",
    "depends": [
        "base",
        "contacts",
        "crm",
        "mail",
        "utm",
        "plasticos_base",
        "plasticos_material_profile",
        "plasticos_facility_profile",
        "plasticos_offer",
        "plasticos_buyer_match_engine",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/intake_views.xml",
        "views/material_profile_intake_views.xml",
        "views/intake_ux.xml",
    ],
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "auto_install": True,
    "application": False,
    "license": "LGPL-3",
}
