{
    "name": "PlasticOS Logistics Automation",
    "version": "19.0.1.0.0",
    "summary": "Deterministic automation layer for logistics: follow-ups, escalations, dispatch tracking",
    "author": "PlasticOS",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "sale_management",
        "purchase",
        "stock",
        "plasticos_logistics",
        "plasticos_transaction",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_templates.xml",
        "data/cron_supplier_followup.xml",
        "data/cron_broker_followup.xml",
        "data/cron_load_sla.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
    ],
    "installable": True,
    "application": False,
}
