{
    "name": "PlasticOS Material Profile",
    "version": "19.0.5.7.0",
    "summary": "Canonical material master registries: polymer, form, color, source, process, grade templates",
    "license": "LGPL-3",
    "author": "Igor Beylin",
    "category": "Operations",
    "depends": [
        "plasticos_base",
        "base",
        "contacts",
        "mail",
        "purchase",
        "sale_management",
        "product",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/filler_type_data.xml",
        "data/material_attribute_data.xml",
        "data/packaging_type_data.xml",
        "data/polymer_data.xml",
        "data/material_form_data.xml",
        "data/material_color_data.xml",
        "data/source_type_data.xml",
        "data/process_type_data.xml",
        "data/grade_template_data.xml",
        "views/polymer_views.xml",
        "views/grade_template_views.xml",
        "views/material_form_views.xml",
        "views/material_color_views.xml",
        "views/source_type_views.xml",
        "views/process_type_views.xml",
        "views/material_profile_views.xml",
        "views/material_profile_ux.xml",
        "views/partner_material_ux.xml",
    ],
    "installable": True,
    "auto_install": True,
    "application": False,
}
