{
    "name": "Plasticos Partner Import",
    "version": "19.0.2.1.0",
    "summary": "Deterministic partner + CRM lead import with wizard UI (Odoo 19)",
    "author": "Igor Beylin",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "account",
        "crm",
        "utm",
        "plasticos_facility_profile",
        "plasticos_crm_bridge",
        "plasticos_intake",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/partner_import_wizard_views.xml",
        "views/partner_bulk_update_wizard_views.xml",
        "views/crm_lead_import_wizard_views.xml",
    ],
    "installable": True,
    "auto_install": True,
    "application": False,
}
