{
    "name": "PlasticOS Base",
    "version": "19.0.1.1.3",
    "summary": "Core seed data, feature gates, and microservice integration",
    "license": "LGPL-3",
    "author": "Igor Beylin",
    "category": "PlasticOS",
    "depends": [
        "base",
        "base_setup",
        "contacts",
        "sale_management",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/menu.xml",
        "data/company.xml",
        "data/service_user.xml",
        "data/admin_users.xml",
        "data/partner_tags.xml",
        "data/material_taxonomy.xml",
        "data/sales_reps.xml",
        "data/attachment_maintenance_cron.xml",
        "data/midnight_recompute_cron.xml",
        "data/feature_flags.xml",
        "views/res_config_settings_views.xml",
    ],
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "auto_install": False,
}
