"""Canonical keys and statuses for durable web-lead evidence.

Centralizing these keys makes evidence schema evolution explicit and avoids
mistaking JSON evidence keys for Odoo Selection values in repository audits.
"""

KEY_ASSESSMENT = "assessment"
KEY_ACQUISITION_STATUS = "acquisition_status"
KEY_API_KEY = "api_key"
KEY_ATTACHMENTS = "attachments"
KEY_BASE_URL = "base_url"
KEY_CALL_METADATA = "call_metadata"
KEY_CANONICAL_PAYLOAD = "canonical_payload"
KEY_CLASSIFICATION = "classification"
KEY_CLARIFICATION_REQUESTS = "clarification_requests"
KEY_CONFLICTS = "conflicts"
KEY_CONTEXT = "context"
KEY_DETERMINISTIC_CLASSIFICATION = "deterministic_classification"
KEY_DECISION = "decision"
KEY_ECONOMIC_ASSESSMENT = "economic_assessment"
KEY_ECONOMIC_ELIGIBILITY_POLICY = "economic_eligibility_policy"
KEY_ECONOMIC_ELIGIBILITY = "economic_eligibility"
KEY_ERROR = "error"
KEY_ERROR_TYPE = "error_type"
KEY_EVIDENCE = "evidence"
KEY_FACILITY_ID = "facility_id"
KEY_FORM_CODE = "form_code"
KEY_FORM_ID = "form_id"
KEY_ID = "id"
KEY_INTAKE = "intake"
KEY_IR_ATTACHMENT_ID = "ir_attachment_id"
KEY_LEAD = "lead"
KEY_LEAD_ID = "lead_id"
KEY_LOADS_PER_MONTH = "loads_per_month"
KEY_MODEL = "model"
KEY_NAME = "name"
KEY_PARTNER_ID = "partner_id"
KEY_PENDING_COMPANY_NAME = "pending_company_name"
KEY_POLYMER_CODE = "polymer_code"
KEY_POLYMER_ID = "polymer_id"
KEY_PROVIDER = "provider"
KEY_PROVIDER_EXTERNAL_ID = "provider_external_id"
KEY_QUANTITY = "quantity"
KEY_QUANTITY_PER_LOAD_LBS = "quantity_per_load_lbs"
KEY_REASON = "reason"
KEY_REASONS = "reasons"
KEY_RECONCILED_EVIDENCE = "reconciled_evidence"
KEY_REVIEW_NOTES = "review_notes"
KEY_REVIEW_REASONS = "review_reasons"
KEY_REVIEW_REQUIRED = "review_required"
KEY_ROLE = "role"
KEY_SCHEMA_VERSION = "schema_version"
KEY_SELLER_MATERIAL_AND_SUPPLY = "seller_material_and_supply"
KEY_STATUS = "status"
KEY_SOURCE_ID = "source_id"
KEY_SOURCE_TYPE_CODE = "source_type_code"
KEY_SOURCE_TYPE_ID = "source_type_id"
KEY_TRANSPORT = "transport"
KEY_TEMPERATURE = "temperature"
KEY_VISION = "vision"
KEY_WORKSPACE_ID = "workspace_id"
KEY_HOT_QUALIFIERS = "hot_qualifiers"
KEY_CONTENT_SHA256 = "content_sha256"

ASSESSMENT_STATUS_ASSESSED = "assessed"
ASSESSMENT_STATUS_UNAVAILABLE = "unavailable"
