{
    "name": "Plasticos Logistics Engine",
    "version": "19.0.1.2.1",
    "summary": "Load management and dispatch",
    "author": "Igor Beylin",
    "license": "LGPL-3",
    "depends": ["plasticos_base", "plasticos_transaction", "sale_management", "stock", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/incoterms.xml",
        "data/sequence.xml",
        "data/cron.xml",
        "views/load_views.xml",
        "views/load_dashboard_views.xml",
        "views/sale_order_button.xml",
        "views/load_bulk_update_wizard_views.xml",
        "views/load_ux.xml",
        "views/transaction_load_views.xml",
        "report/load_reports.xml",
        "report/report_bol_pickup.xml",
        "report/report_bol_delivery.xml",
        "report/report_delivery_order.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "auto_install": True,
}
