{
    "name": "Plasticos Logistics Engine",
    "version": "19.0.1.0.0",
    "summary": "Load management and dispatch",
    "author": "PlasticOS",
    "license": "LGPL-3",
    "depends": ["sale_management", "stock", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/load_views.xml",
        "views/sale_order_button.xml",
        "data/cron.xml",
        "report/load_reports.xml",
        "report/report_bol_pickup.xml",
        "report/report_bol_delivery.xml",
        "report/report_delivery_order.xml",
    ],
    "installable": True,
    "application": False,
}
