{
    "name": "Plasticos Transaction Spine",
    "version": "19.0.2.1.0",
    "summary": "Core transaction lifecycle management with integrated commission engine",
    "author": "PlasticOS",
    "license": "LGPL-3",
    "depends": [
        "plasticos_base",
        "base",
        "mail",
        "product",
        "account",
        "sale_management",
        "purchase",
        "plasticos_logistics",
        "plasticos_material_profile",
        "plasticos_facility_profile",
        "plasticos_intake",
        "plasticos_product",
        "plasticos_offer",
        "plasticos_matching",
    ],
    "data": [
        "security/security_hardening.xml",
        "security/ir.model.access.csv",
        "security/commission_acl.xml",
        "data/sequence.xml",
        "data/audit_cron.xml",
        "views/transaction_views.xml",
        "views/commission_views.xml",
        "views/transaction_bulk_update_wizard_views.xml",
        "views/transaction_bulk_assign_wizard_views.xml",
        "views/transaction_import_wizard_views.xml",
        "views/transaction_ux.xml",
        "views/transaction_bridge_views.xml",
        "views/intake_bridge_views.xml",
        "views/partner_bridge_views.xml",
        "views/offer_bridge_views.xml",
        "views/match_result_bridge_views.xml",
    ],
    "installable": True,
    "application": False,
}
