[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo
addons_path = /mnt/extra-addons,/mnt/enterprise,/usr/lib/python3/dist-packages/odoo/addons
without_demo = True
list_db = False
proxy_mode = False
