{
    "name": "PlastOS CRM Bridge",
    "version": "19.0.2.3.1",
    "author": "Igor Beylin",
    "summary": "CRM integration for plastics brokerage workflow",
    "depends": [
        "crm",
        "utm",
        "plasticos_security_base",
        "plasticos_web_leads",
        # "plasticos_matching",  # Disabled - external microservice
        "plasticos_material_profile",
        "plasticos_facility_profile",
        "plasticos_transaction",
        "plasticos_logistics",
        "plasticos_intake",
    ],
    "data": [
        "security/crm_group_imply.xml",
        "security/ir.model.access.csv",
        "data/crm_stage_data.xml",
        "data/partner_category_data.xml",
        "data/lead_source_data.xml",
        "data/utm_source_deactivate.xml",
        "views/crm_lead_views.xml",
        "views/material_profile_views.xml",
    ],
    "category": "PlastOS",
    "license": "LGPL-3",
    "installable": True,
    "auto_install": True,
}
