{
    "name": "PlastOS CRM Bridge",
    "version": "19.0.2.0.0",
    "author": "PlasticOS",
    "summary": "CRM integration for plastics brokerage workflow",
    "depends": [
        "crm",
        "utm",
        "plasticos_web_leads",
        "plasticos_matching",
        "plasticos_material_profile",
        "plasticos_transaction",
        "plasticos_logistics",
        "plasticos_intake",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/crm_stage_data.xml",
        "data/partner_category_data.xml",
        "data/lead_source_data.xml",
        "views/crm_lead_views.xml",
        "views/material_profile_views.xml",
    ],
    "category": "PlastOS",
    "license": "LGPL-3",
}
