{
    "name": "PlasticOS Semantic Kernel",
    "version": "19.0.1.0.3",
    "summary": "Additive semantic models for PlasticOS material and facility kernel.",
    "license": "LGPL-3",
    "author": "Igor Beylin",
    "category": "Plasticos/Semantic",
    "depends": [
        "mail",
        "plasticos_material_profile",
        "plasticos_facility_profile",
        "plasticos_intake",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/material_specification_views.xml",
        "views/material_observation_views.xml",
        "views/supply_opportunity_views.xml",
        "views/buyer_demand_views.xml",
        "views/facility_material_rule_views.xml",
        "views/capacity_observation_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
