#!/usr/bin/env python3
"""Build PR description from commits and diff vs base branch."""

from __future__ import annotations

import subprocess
import sys


def _run(*args: str) -> str:
    return subprocess.check_output(args, text=True).strip()


def build_body(base: str) -> str:
    title = _run("git", "log", "-1", "--pretty=%s")
    try:
        commits = _run("git", "log", f"origin/{base}..HEAD", "--pretty=format:- %s")
    except subprocess.CalledProcessError:
        commits = f"- {title}"
    if not commits:
        commits = f"- {title}"
    try:
        stat = _run("git", "diff", f"origin/{base}...HEAD", "--stat")
    except subprocess.CalledProcessError:
        stat = _run("git", "show", "--stat", "--oneline", "-1")

    return f"""## Summary
{commits}

## Changes
```
{stat}
```

## Test plan
- [ ] CI Gate (`ci.yml`) green
- [ ] Odoo.sh checks (if applicable)
- [ ] Module upgrade validated on staging if schema changed

---
_Auto-generated by `make push` (github push kernel) → base `{base}`._
"""


def main() -> int:
    base = sys.argv[1] if len(sys.argv) > 1 else "Staging"
    print(build_body(base))
    return 0


if __name__ == "__main__":
    sys.exit(main())
