#!/usr/bin/env python3
"""
GMP Report Generator — Creates canonical GMP reports.

Usage:
    python3 scripts/generate_gmp_report.py \
        --task "Task description" \
        --tier RUNTIME_TIER \
        --todo "T1|file.py|1-10|REPLACE|Description" \
        --validation "lint|✅" \
        --summary "Summary text" \
        --skip-verify
"""

import argparse
from datetime import datetime
from pathlib import Path


def generate_report(
    task: str,
    tier: str,
    todos: list[str],
    validations: list[str],
    summary: str,
    gmp_id: str | None = None,
) -> str:
    """Generate a GMP report in markdown format."""

    # Generate GMP ID if not provided
    if not gmp_id:
        gmp_id = f"GMP-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    # Parse todos
    todo_rows = []
    for todo in todos:
        parts = todo.split("|")
        if len(parts) >= 4:
            todo_rows.append(
                {
                    "id": parts[0],
                    "file": parts[1],
                    "lines": parts[2],
                    "action": parts[3],
                    "desc": parts[4] if len(parts) > 4 else "",
                }
            )

    # Parse validations
    val_rows = []
    for val in validations:
        parts = val.split("|")
        if len(parts) >= 2:
            val_rows.append(
                {
                    "gate": parts[0],
                    "result": parts[1],
                }
            )

    # Build report
    report = f"""# GMP Report: {gmp_id}

**Task:** {task}
**Tier:** {tier}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Status:** COMPLETED

---

## Summary

{summary}

---

## TODO Plan

| # | File | Lines | Action | Description |
|---|------|-------|--------|-------------|
"""

    for t in todo_rows:
        report += f"| {t['id']} | `{t['file']}` | {t['lines']} | {t['action']} | {t['desc']} |\n"

    report += """
---

## Validation Results

| Gate | Result |
|------|--------|
"""

    for v in val_rows:
        report += f"| {v['gate']} | {v['result']} |\n"

    report += """
---

## Phase Completion

- [x] Phase 0: Scope Lock
- [x] Phase 1: Baseline
- [x] Phase 2: Implement
- [x] Phase 3: Enforce
- [x] Phase 4: Validate
- [x] Phase 5: Recursive Verify
- [x] Phase 6: Finalize

---

*Generated by GMP Executor*
"""

    return report


def main():
    parser = argparse.ArgumentParser(description="Generate GMP Report")
    parser.add_argument("--task", required=True, help="Task description")
    parser.add_argument("--tier", required=True, help="Tier (KERNEL_TIER, RUNTIME_TIER, etc)")
    parser.add_argument("--todo", action="append", default=[], help="TODO item (T#|file|lines|action|desc)")
    parser.add_argument("--validation", action="append", default=[], help="Validation (gate|result)")
    parser.add_argument("--summary", default="", help="Summary text")
    parser.add_argument("--gmp-id", default=None, help="GMP ID (auto-generated if not provided)")
    parser.add_argument("--update-workflow", action="store_true", help="Update workflow_state.md")
    parser.add_argument("--skip-verify", action="store_true", help="Skip verification")

    args = parser.parse_args()

    # Generate report
    report = generate_report(
        task=args.task,
        tier=args.tier,
        todos=args.todo,
        validations=args.validation,
        summary=args.summary,
        gmp_id=args.gmp_id,
    )

    # Determine output path
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    # Create filename from task
    task_slug = args.task[:50].replace(" ", "-").replace("/", "-")
    gmp_id = args.gmp_id or f"GMP-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    filename = f"GMP-Report-{gmp_id.replace('GMP-', '')}-{task_slug}.md"

    output_path = (reports_dir / filename).resolve()
    # Containment guard: CLI-derived slug must not escape reports/ (SonarCloud S8707)
    if not output_path.is_relative_to(reports_dir.resolve()):
        raise ValueError(f"Refusing to write outside reports/: {output_path}")
    output_path.write_text(report)

    print(f"Report saved: {output_path}")
    return str(output_path)


if __name__ == "__main__":
    main()
