#!/usr/bin/env python3
"""
Odoo Module Dependency & XML ID Audit
Finds missing dependencies, broken XML ID references, and view inheritance issues.
"""

import ast
import json
import re
from collections import defaultdict
from pathlib import Path

ODOO_CORE_MODULES = {
    "base",
    "mail",
    "sale",
    "sale_management",
    "purchase",
    "stock",
    "account",
    "crm",
    "contacts",
    "product",
    "hr",
    "project",
    "website",
    "mrp",
    "fleet",
    "calendar",
    "note",
    "survey",
    "event",
    "helpdesk",
    "quality",
    "maintenance",
    "base_automation",
    "utm",
    "web",
    "bus",
    "digest",
    "iap",
    "portal",
    "auth_signup",
    "resource",
    "uom",
    "payment",
    "board",
    "fetchmail",
    "sms",
    "phone_validation",
    "snailmail",
    "partner_autocomplete",
    "google_calendar",
    "microsoft_calendar",
    "documents",  # Odoo Enterprise module
}


class OdooAudit:
    def __init__(self, root_dir="."):
        self.root_dir = Path(root_dir)
        self.modules = {}
        self.xmlid_defs = defaultdict(set)  # module -> set of xmlids
        self.xmlid_refs = defaultdict(list)  # xmlid -> [(file, line, module)]
        self.view_inherits = []  # [(child_module, parent_xmlid, file, line)]

    def scan_modules(self):
        """Find all Odoo modules (directories with __manifest__.py)"""
        for manifest in self.root_dir.rglob("__manifest__.py"):
            module_dir = manifest.parent
            module_name = module_dir.name

            # Skip docs, patches, and test directories
            if any(part in str(manifest) for part in ["/docs/", "/patches/", "/test_"]):
                continue

            with open(manifest) as f:
                try:
                    manifest_data = ast.literal_eval(f.read())
                    self.modules[module_name] = {
                        "path": module_dir,
                        "depends": manifest_data.get("depends", []),
                        "data": manifest_data.get("data", []),
                    }
                except Exception as e:
                    print(f"⚠️  Failed to parse {manifest}: {e}")

    def scan_xmlid_definitions(self):
        """Extract all XML ID definitions from <record id="...">"""
        for module_name, module_data in self.modules.items():
            module_path = module_data["path"]

            for xml_file in module_path.rglob("*.xml"):
                with open(xml_file, encoding="utf-8") as f:
                    for _line_num, line in enumerate(f, 1):
                        # Match <record id="view_name" ...>
                        match = re.search(r'<record\s+id="([^"]+)"', line)
                        if match:
                            xmlid = match.group(1)
                            self.xmlid_defs[module_name].add(xmlid)

    def scan_xmlid_references(self):
        """Extract all XML ID references from ref="module.xmlid" """
        for module_name, module_data in self.modules.items():
            module_path = module_data["path"]

            for xml_file in module_path.rglob("*.xml"):
                with open(xml_file, encoding="utf-8") as f:
                    for line_num, line in enumerate(f, 1):
                        # Match ref="module.xmlid"
                        for match in re.finditer(r'ref="([^"]+)"', line):
                            xmlid = match.group(1)
                            self.xmlid_refs[xmlid].append(
                                (str(xml_file.relative_to(self.root_dir)), line_num, module_name)
                            )

                        # Track view inheritance specifically
                        if "inherit_id" in line:
                            match = re.search(r'ref="([^"]+)"', line)
                            if match:
                                parent_xmlid = match.group(1)
                                self.view_inherits.append(
                                    (module_name, parent_xmlid, str(xml_file.relative_to(self.root_dir)), line_num)
                                )

    def check_dangling_refs(self):
        """Find XML IDs that are referenced but not defined"""
        errors = []

        for xmlid, references in self.xmlid_refs.items():
            if "." not in xmlid:
                # External reference without module prefix (odoo core)
                continue

            # Skip model_* XML IDs - these are auto-generated by Odoo from ir.model.access.csv
            if xmlid.split(".", 1)[1].startswith("model_"):
                continue

            module, record_id = xmlid.split(".", 1)

            # Check if the module exists (skip Odoo core modules)
            if module not in self.modules:
                if module in ODOO_CORE_MODULES:
                    continue  # Skip Odoo core modules
                for file, line, ref_module in references:
                    errors.append(
                        {
                            "type": "MISSING_MODULE",
                            "severity": "CRITICAL",
                            "xmlid": xmlid,
                            "module": module,
                            "file": file,
                            "line": line,
                            "referencing_module": ref_module,
                            "message": f"Module '{module}' not found in codebase",
                        }
                    )
                continue

            # Check if the XML ID is defined in that module
            if record_id not in self.xmlid_defs[module]:
                for file, line, ref_module in references:
                    errors.append(
                        {
                            "type": "MISSING_XMLID",
                            "severity": "CRITICAL",
                            "xmlid": xmlid,
                            "file": file,
                            "line": line,
                            "referencing_module": ref_module,
                            "message": f"XML ID '{record_id}' not defined in module '{module}'",
                        }
                    )

        return errors

    def check_missing_dependencies(self):
        """Find modules that reference other modules without declaring dependency"""
        errors = []

        for child_module, parent_xmlid, file, line in self.view_inherits:
            if "." not in parent_xmlid:
                continue

            parent_module = parent_xmlid.split(".")[0]

            # Skip self-references and Odoo core modules
            if parent_module == child_module:
                continue
            if parent_module in ODOO_CORE_MODULES:
                continue  # Odoo core modules are always available

            # Check if dependency is declared
            depends = self.modules[child_module]["depends"]
            if parent_module not in depends:
                errors.append(
                    {
                        "type": "MISSING_DEPENDENCY",
                        "severity": "CRITICAL",
                        "child_module": child_module,
                        "parent_module": parent_module,
                        "parent_xmlid": parent_xmlid,
                        "file": file,
                        "line": line,
                        "message": (
                            f"Module '{child_module}' inherits from '{parent_module}' but doesn't declare it in depends"
                        ),
                        "fix": f"Add '{parent_module}' to depends list in {child_module}/__manifest__.py",
                    }
                )

        return errors

    def check_data_file_loading(self):
        """Find XML files that define records but aren't listed in __manifest__.py data"""
        errors = []

        for module_name, module_data in self.modules.items():
            module_path = module_data["path"]
            data_files = set(module_data["data"])

            # Find all XML files with <record> tags
            for xml_file in module_path.rglob("*.xml"):
                rel_path = str(xml_file.relative_to(module_path))

                with open(xml_file, encoding="utf-8") as f:
                    content = f.read()
                    if "<record" in content and rel_path not in data_files:
                        errors.append(
                            {
                                "type": "UNLOADED_DATA_FILE",
                                "severity": "HIGH",
                                "module": module_name,
                                "file": rel_path,
                                "message": "File defines <record> tags but not listed in __manifest__.py data",
                                "fix": f"Add '{rel_path}' to data list in {module_name}/__manifest__.py",
                            }
                        )

        return errors

    def run_audit(self):
        """Run full audit and return all errors"""
        print("🔍 Scanning modules...")
        self.scan_modules()
        print(f"   Found {len(self.modules)} modules")

        print("🔍 Scanning XML ID definitions...")
        self.scan_xmlid_definitions()
        total_defs = sum(len(v) for v in self.xmlid_defs.values())
        print(f"   Found {total_defs} XML ID definitions")

        print("🔍 Scanning XML ID references...")
        self.scan_xmlid_references()
        print(f"   Found {len(self.xmlid_refs)} unique XML ID references")

        print("\n📋 Running checks...\n")

        all_errors = []

        print("   ⚙️  Checking for dangling XML ID references...")
        errors = self.check_dangling_refs()
        all_errors.extend(errors)
        print(f"      Found {len(errors)} errors")

        print("   ⚙️  Checking for missing dependencies...")
        errors = self.check_missing_dependencies()
        all_errors.extend(errors)
        print(f"      Found {len(errors)} errors")

        print("   ⚙️  Checking for unloaded data files...")
        errors = self.check_data_file_loading()
        all_errors.extend(errors)
        print(f"      Found {len(errors)} errors")

        return all_errors

    def generate_report(self, errors):
        """Generate human-readable report"""
        if not errors:
            print("\n✅ No errors found! Your module dependencies are clean.\n")
            return

        print(f"\n❌ Found {len(errors)} issues:\n")

        # Group by severity
        by_severity = defaultdict(list)
        for error in errors:
            by_severity[error["severity"]].append(error)

        for severity in ["CRITICAL", "HIGH", "MODERATE", "LOW"]:
            if severity not in by_severity:
                continue

            print(f"\n{'=' * 80}")
            print(f"{severity} ISSUES ({len(by_severity[severity])})")
            print(f"{'=' * 80}\n")

            for i, error in enumerate(by_severity[severity], 1):
                print(f"{i}. [{error['type']}] {error['message']}")
                print(f"   File: {error['file']}")
                if "line" in error:
                    print(f"   Line: {error['line']}")
                if "fix" in error:
                    print(f"   Fix: {error['fix']}")
                print()


if __name__ == "__main__":
    import sys

    root_dir = sys.argv[1] if len(sys.argv) > 1 else "."

    auditor = OdooAudit(root_dir)
    errors = auditor.run_audit()
    auditor.generate_report(errors)

    # Save JSON report
    with open("odoo_audit_report.json", "w") as f:
        json.dump(errors, f, indent=2)

    print("📄 Full report saved to odoo_audit_report.json")

    sys.exit(1 if errors else 0)
