{
    "name": "Plasticos Documents Engine",
    "version": "19.0.2.0.0",
    "summary": "Document management, compliance, validation matrix, and transaction doc tracking",
    "author": "PlasticOS",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "plasticos_transaction",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/document_tag_views.xml",
        "views/document_rule_views.xml",
        "views/document_views.xml",
        "views/document_extension_views.xml",
        "views/validation_matrix_views.xml",
        "views/transaction_docs_views.xml",
        "data/cron.xml",
        "data/document_tags_data.xml",
        "data/cron_missing_docs.xml",
    ],
    "installable": True,
    "application": False,
}
