{
    "name": "PlasticOS Commission Engine",
    "version": "19.0.1.2.0",
    "summary": "Commission rules, payout management, and sales rep deal dashboard",
    "author": "Igor Beylin",
    "license": "LGPL-3",
    "category": "Plasticos/Sales",
    "depends": [
        "plasticos_base",
        "plasticos_transaction",
        "plasticos_logistics",
        "plasticos_security_base",
        "plasticos_documents_native",
        "base",
        "product",
        "mail",
    ],
    "data": [
        "security/commission_group.xml",
        "security/ir.model.access.csv",
        "data/commission_payout_sequence.xml",
        "views/commission_rule_views.xml",
        "views/commission_payout_views.xml",
        "views/sales_dashboard_views.xml",
        "views/transaction_commission_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": True,
}
