{
    "name": "PlasticOS Facility Profile",
    "version": "19.0.4.1.0",
    "summary": "Facility capability profiles — equipment, tolerances, and BCP fields",
    "license": "LGPL-3",
    "author": "PlasticOS",
    "category": "Hidden",
    "depends": [
        "base",
        "contacts",
        "mail",
        "sale_management",
        "utm",
        "plasticos_material_profile",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/equipment_type_data.xml",
        "data/partner_type_data.xml",
        "views/partner_type_views.xml",
        "views/facility_profile_views.xml",
        "views/facility_profile_ux.xml",
        "views/partner_ux.xml",
    ],
    "installable": True,
    "auto_install": True,
    "application": False,
}
